# Generated by Django 2.0 on 2021-08-21 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('tipo_documento', models.CharField(choices=[('ti', 'Tarjeta de identidad'), ('cc', 'Cedula de ciudadania')], max_length=50, verbose_name='Tipo de documento')),
                ('numero_documento', models.IntegerField(unique=True, verbose_name='Numero de documento')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('ocupacion', models.CharField(max_length=50)),
                ('entrenador', models.BooleanField(default='False')),
                ('admin', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('direccion', models.CharField(default='', max_length=250)),
                ('telefono', models.CharField(default='', max_length=250)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionMedica',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('altura', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=50)),
                ('enfermedad', models.CharField(max_length=150)),
                ('alergia', models.CharField(max_length=150)),
                ('operaciones', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuarios.Plan'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuarios.Sucursal'),
        ),
    ]
