# Generated by Django 2.0 on 2021-08-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(null=True, verbose_name='Edad'),
        ),
    ]
