# Generated by Django 2.0 on 2021-08-21 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0002_auto_20210821_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ocupacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlUsuarios.Plan'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlUsuarios.Sucursal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('ti', 'Tarjeta de identidad'), ('cc', 'Cedula de ciudadania')], max_length=50, null=True, verbose_name='Tipo de documento'),
        ),
    ]
