# Generated by Django 2.0 on 2021-02-25 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0002_auto_20210225_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionmedica',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='controlUsuarios.Usuario'),
        ),
    ]
