# Generated by Django 2.0 on 2021-02-25 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0003_auto_20210225_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracionmedica',
            name='id',
        ),
        migrations.AlterField(
            model_name='valoracionmedica',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='controlUsuarios.Usuario'),
        ),
    ]
