# Generated by Django 2.0 on 2021-08-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0003_auto_20210821_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='entrenador',
            field=models.BooleanField(default=False),
        ),
    ]
