# Generated by Django 2.0 on 2021-08-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0004_auto_20210225_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='usuario',
            name='entrenador',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
