# Generated by Django 2.0 on 2021-08-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0005_auto_20210828_1221'),
        ('controlUsuarios', '0004_auto_20210822_1004'),
    ]

    operations = [
    ]
