# Generated by Django 2.0 on 2021-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0006_merge_20210828_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='meses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses a pagar'),
        ),
    ]
