# Generated by Django 2.0 on 2021-08-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0007_usuario_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
