# Generated by Django 2.0 on 2021-08-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0007_usuario_meses'),
        ('controlUsuarios', '0004_auto_20210822_1503'),
    ]

    operations = [
    ]
