# Generated by Django 2.0 on 2021-09-21 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0008_plan_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, verbose_name='Ejercicio')),
                ('duracion', models.CharField(max_length=254, verbose_name='Duracion')),
                ('series', models.CharField(max_length=254, verbose_name='Series')),
                ('repeticiones', models.CharField(max_length=254, verbose_name='Repeticiones por serie')),
                ('descanso', models.CharField(max_length=254, verbose_name='Descanso')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, verbose_name='Rutina')),
                ('Domingo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='domingo', to='controlUsuarios.Ejercicios')),
                ('Jueves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jueves', to='controlUsuarios.Ejercicios')),
                ('Martes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='martes', to='controlUsuarios.Ejercicios')),
                ('Miercoles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miercoles', to='controlUsuarios.Ejercicios')),
                ('Sabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabado', to='controlUsuarios.Ejercicios')),
                ('Viernes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viernes', to='controlUsuarios.Ejercicios')),
                ('lunes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunes', to='controlUsuarios.Ejercicios')),
            ],
        ),
        migrations.AlterField(
            model_name='valoracionmedica',
            name='usuario',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
