# Generated by Django 2.0 on 2021-09-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0009_auto_20210921_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='lunes',
        ),
        migrations.AddField(
            model_name='rutina',
            name='lunes',
            field=models.ManyToManyField(to='controlUsuarios.Ejercicios'),
        ),
    ]
