# Generated by Django 2.0 on 2021-09-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0010_auto_20210921_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='Domingo',
        ),
        migrations.AddField(
            model_name='rutina',
            name='Domingo',
            field=models.ManyToManyField(blank=True, related_name='domingo', to='controlUsuarios.Ejercicios'),
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='Jueves',
        ),
        migrations.AddField(
            model_name='rutina',
            name='Jueves',
            field=models.ManyToManyField(related_name='jueves', to='controlUsuarios.Ejercicios'),
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='Martes',
        ),
        migrations.AddField(
            model_name='rutina',
            name='Martes',
            field=models.ManyToManyField(related_name='martes', to='controlUsuarios.Ejercicios'),
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='Miercoles',
        ),
        migrations.AddField(
            model_name='rutina',
            name='Miercoles',
            field=models.ManyToManyField(related_name='miercoles', to='controlUsuarios.Ejercicios'),
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='Sabado',
        ),
        migrations.AddField(
            model_name='rutina',
            name='Sabado',
            field=models.ManyToManyField(related_name='sabado', to='controlUsuarios.Ejercicios'),
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='Viernes',
        ),
        migrations.AddField(
            model_name='rutina',
            name='Viernes',
            field=models.ManyToManyField(related_name='viernes', to='controlUsuarios.Ejercicios'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='lunes',
            field=models.ManyToManyField(related_name='lunes', to='controlUsuarios.Ejercicios'),
        ),
    ]
