# Generated by Django 2.0 on 2021-09-21 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0011_auto_20210921_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlUsuarios.Rutina'),
        ),
    ]
