# Generated by Django 2.0 on 2021-09-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuarios', '0013_usuario_foto'),
        ('controlUsuarios', '0008_merge_20210829_1555'),
    ]

    operations = [
    ]
